version: '3'
services:
  k6:
    image: grafana/k6:latest
    ports:
      - "6565:6565"
    volumes:
      - ./k6:/scripts
    working_dir: /scripts
    entrypoint: [ "k6", "run", "--out", "influxdb=http://localhost:8086/hhplus" ]
    network_mode: host

