version: '3'
services:

  mysql1:
    image: mysql:8.0
    container_name: mysql1
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_backup.sql:/docker-entrypoint-initdb.d/mysql-backup.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus

  mysql2:
    image: mysql:8.0
    container_name: mysql2
    ports:
      - "3309:3306"
    volumes:
      - ./mysql_backup.sql:/docker-entrypoint-initdb.d/mysql-backup.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
networks:
  default:
    driver: bridge